# Generated by Django 3.2.9 on 2021-12-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_filial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='filial',
            name='open_times',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='filial',
            name='orienter',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='filial',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
