# Generated by Django 3.2.9 on 2021-12-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20211209_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(null=True, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='photo',
            field=models.ImageField(upload_to='banners'),
        ),
    ]
