# Generated by Django 3.2.9 on 2021-12-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_auth', '0005_smscode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smscode',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.AlterField(
            model_name='smscode',
            name='code',
            field=models.IntegerField(default=417439, null=True),
        ),
    ]
