# Generated by Django 3.2.9 on 2021-12-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_auth', '0006_auto_20211211_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='smscode',
            name='code',
            field=models.IntegerField(default=529919, null=True),
        ),
    ]
