# Generated by Django 3.2.9 on 2021-12-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_auth', '0007_auto_20211211_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smscode',
            name='code',
            field=models.IntegerField(default=742188, null=True, unique=True),
        ),
    ]
