# Generated by Django 3.2.9 on 2021-12-11 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_auth', '0009_alter_smscode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='smscode',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 11, 22, 45, 32, 108238), null=True),
        ),
    ]
