# Generated by Django 3.2.9 on 2021-12-11 23:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_auth', '0010_smscode_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smscode',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 11, 23, 52, 23, 512773), null=True),
        ),
    ]
